### ISSUE TITLE
Add scalaz-sbt plugin

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-ioqueue#18]
Add scalaz-sbt plugin to have a unified dependencies in scalaz projects.
It is an SBT build plug-in that allows common build configuration across all Scalaz 8 libraries.

- [ ] under `Project` create a new file: `build.sbt` which contains:
```scala
dependsOn(RootProject(uri("git:https://github.com/scalaz/scalaz-sbt.git")))
```

- [ ]  refactor `build.sbt`
After this PR will be merged: https://github.com/scalaz/scalaz-sbt/pull/18,  we can remove `resolvers += "Sonatype OSS Snapshots".at("https://oss.sonatype.org/content/repositories/snapshots")` too

- [ ] remove `ScalazBuild` (we will not need it anymore, every build configuration would be in `scalaz-sbt` plugin)

**Comment by vil1** [comment]
The related PR has been merged on scalaz-sbt

**Comment by randbw** [comment]
I'll give this a go
