### ISSUE TITLE
Implement shutdown

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-ioqueue#25]
- [x] Add a new QueueState called Shutdown which stores a list of throwable.

- [x] Implement shutdown methods that interrupt the present takers and putters and put the queue on the Shutdown state (any attempt to take or offer to a Shutdown queue will terminate a fiber that attempts to do this operation with a list of throwables): 
```scala
def shutdown: IO[Nothing, Unit] = shutdown0(Nil)
def shutdown(t: Throwable, ts: Throwable*): IO[Nothing, Unit] =
  shutdown0(t :: ts.toList)
def shutdown0(l: List[Throwable]): IO[Nothing, Unit] = ???
```

**Comment by ghostdogpr** [comment]
I'm implementing this one (mostly done) 😀

A couple questions:
- If we shutdown a queue that's already in the Shutdown state, it will just replace the list of throwables, is that correct?
- Should takeAll and takeUpTo return an empty list if called on a shutdown queue?

**Comment by jdegoes** [comment]
> If we shutdown a queue that's already in the Shutdown state, it will just replace the list of throwables, is that correct?

It should have no effect, not replace the list of throwables.

> Should takeAll and takeUpTo return an empty list if called on a shutdown queue?

If you `take*` or `offer*` on any shutdown queue, it must terminate the fiber with the list of throwables. Shutdown queues will terminate anyone who interacts with them.

**Comment by ghostdogpr** [comment]
Got it, thanks.

I'll submit the PR once #23 is merged because the current master doesn't build (pointing at the snapshot version which has changed).

**Comment by wi101** [comment]
@ghostdogpr #23 is merged :)
