### ISSUE TITLE
offerAll should return false if not all elements are offered in Sliding strategy

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-ioqueue#38]
`offerAll` returns `IO[Nothing, Boolean]` 
* in `Backpressure` it returns always true
* in `Sliding`  it returns `true` only if all elements on the list are successfully added otherwise `false`
* in `Dropping` it returns `true` only if no elements is dropped from the queue = all elements are added in the queue otherwise `false`
 
Thanks @jdegoes

**Comment by randbw** [comment]
I have a PR waiting for this once #15 is merged 😃
