### ISSUE TITLE
Grab Queue from scalaz-zio

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-ioqueue#5]
There is a first version of io- `Queue` in scalaz-zio project.
In scalaz-ioqueue, we will get started from that then improve it and add new features on it. 

So we need to include `Queue`and `QueueSpec` (in a package `scalaz.ioqueue`) and add some test cases which makes it easier to understand the existing code and how it works. 

- [x] add dependency with scalaz-zio.
- [x] include `Queue` & `QueueSpec`.

**Comment by LukaszByczynski** [comment]
if you don't mind i will take this task.

**Comment by wi101** [comment]
Sure :)

**Comment by wi101** [comment]
Feel free to ask any question

**Comment by LukaszByczynski** [comment]
#10
