### ISSUE TITLE
Implement offerAll

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-ioqueue#6]
It would be like:
```scala
final def offerAll(as: TraversableOnce[A]): IO[Nothing, Unit] = ???
```
 to be able to produce a set of values instead of calling offer(a: A) for each element.

**Comment by ashabhasa** [comment]
If it's ok, I would like to work on this.

**Comment by ashabhasa** [comment]
@wi101 here is my first implmentation https://github.com/ashabhasa/scalaz-ioqueue/commit/6d11639b1f8ecf77d5ae6b7d161ae898ab9bfa85

**Comment by ashabhasa** [comment]
@wi101 If the proposed implementation is ok, i would proceed with the creation of a PR.

**Comment by wi101** [comment]
@ashabhasa I added some comments can you see them, and then you can open your PR

**Comment by ashabhasa** [comment]
@wi101 Thank you for you review. I added a commit and some comments.

**Comment by wi101** [comment]
@ashabhasa I saw now your comment and answer it
