### ISSUE TITLE
Implement takeUpTo

### ISSUE THREAD

**Issue by wi101** [scalaz/scalaz-ioqueue#7]
It would be like:
```scala
 final def drainUpTo(max: Int): IO[Nothing, Array[A]] = ???  
```
to take (and dequeue) n element from the queue, instead of calling n times `queue.take`

**Comment by afsalthaj** [comment]
Is it ok if I start on this issue ?

**Comment by LukaszByczynski** [comment]
sure, you can take it. I suggest you start working at top of my PR #10 (create separate branch). After merge, you can easily rebase.

**Comment by wi101** [comment]
@afsalthaj I suggest to open your PR from your fork instead of creating a new branch.
Let's wait the PR of Lukasz to be merged. :)

**Comment by wi101** [comment]
@afsalthaj I will update the name of this method to `drainUpTo`, you can start working in this issue and feel free to ask questions. :)

**Comment by afsalthaj** [comment]
Thanks for that. I am looking at the above PR #10  though that seems to be closed. I will work on top of it and push another branch

**Comment by afsalthaj** [comment]
@wi101 I am guessing drainUpTo will be in terms of `take`?

**Comment by wi101** [comment]
@afsalthaj yes it is= `takeMany(max: Int)`

**Comment by afsalthaj** [comment]
The semantics of take(max) seems to be unblocking, however, this is my WIP. It will be great if my line of thought is correct.

https://github.com/scalaz/scalaz-ioqueue/compare/master...afsalthaj:drainUpTo
